//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appTiendaP.source.entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_venta
    {
        public int id { get; set; }
        public Nullable<int> venta_id { get; set; }
        public Nullable<int> producto_id { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<float> impuesto { get; set; }
        public Nullable<float> valor_unitario { get; set; }
        public Nullable<float> sub_total { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual venta venta { get; set; }
    }
}
